defaults:
  - backbone: croco

name: noposplat

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

num_surfaces: 1
circular_pad: true
twodgs: true

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 2

gs_params_head_type: dpt_gs