view_sampler:
  name: evaluation
  num_context_views: 2
name: mp3d
roots: [/data1/local_userdata/renjiahui/matterport3d/pano_grf/]
make_baseline_1: false
augment: true

image_shape: [512, 1024]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

max_fov: 100.0

skip_bad_shape: true
near: .45
far: 10.
baseline_scale_bounds: false
shuffle_val: false
test_len: -1
test_chunk_interval: 1

test_datasets:
  # - name: m3d
  #   dis: 0.1
  # - name: m3d
  #   dis: 0.25
  - name: m3d
    dis: 0.5
  - name: m3d
    dis: 0.75
  - name: m3d
    dis: 1.0
  - name: residential
    dis: 0.15
  - name: replica
    dis: 0.5

